# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20161105_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='avatar',
        ),
        migrations.AddField(
            model_name='comment',
            name='avater',
            field=models.FileField(default='static/images/default.png', max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='createtime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
