# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
